### ISSUE TITLE
The beta nuget packages don't work properly on non-dnx projects

### ISSUE THREAD

**Issue by derrickcrowne** [syncromatics/KairosDbClientDotNet#1]
The -beta tagged nuget packages which are being built and pushed on linux seem to have issues working with non-dnx projects on windows. The stable releases are built and pushed from windows and work properly with the older project types.

**Comment by peske** [comment]
Talking about targeting, although I'm still confused with new monikers introduced in .NET, I'm pretty sure that targets in your case are wrong. AFAIK, `dnx451` (one of your targets) is obsolete and should be replaced with `net451` (the same meaning). If this is true than your targets are actually `net451` and `net45` which does not make too much sense.

Also it would be good idea to migrate to .NET Core RC2.

**Comment by derrickcrowne** [comment]
Resolved with #6
